AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: AWS SAM template for the CD4AutoML::Workflow::Deploy resource type

Globals:
  Function:
    Timeout: 300  # docker start-up times can be long for SAM CLI

Resources:
  TypeFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: cd4automl_workflow_deploy.handlers.resource
      Runtime: python3.7
      CodeUri: build/

  TestEntrypoint:
    Type: AWS::Serverless::Function
    Properties:
      Handler: cd4automl_workflow_deploy.handlers.test_entrypoint
      Runtime: python3.7
      CodeUri: build/

